language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mrtaan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mrtaan/react-test npm test

after-success:
  - docker build -t mrtaan/multi-client ./client
  - docker build -t mrtaan/multi-nginx ./nginx
  - docker build -t mrtaan/multi-server ./server
  - docker build -t mrtaan/multi-worker ./worker

  # Login to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push mrtaan/multi-client
  - docker push mrtaan/multi-nginx
  - docker push mrtaan/multi-server
  - docker push mrtaan/multi-worker

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  region: "ap-southeast-1"
  app: "complex"
  env: "Complex-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-068145616535"