language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mrtaan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mrtaan/react-test npm test

after-success:
  - docker build -t mrtaan/multi-client ./client
  - docker build -t mrtaan/multi-nginx ./nginx
  - docker build -t mrtaan/multi-server ./server
  - docker build -t mrtaan/multi-worker ./worker